// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDepozit.Data;

#nullable disable

namespace WebDepozit.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230930214834_Add_MounthlyDepozitReport_Table")]
    partial class Add_MounthlyDepozitReport_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebDepozit.Models.MounthlyDepozitReport", b =>
                {
                    b.Property<int>("MounthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MounthId"));

                    b.Property<double>("MounthDepozit")
                        .HasColumnType("float");

                    b.Property<double>("MounthlyIncome")
                        .HasColumnType("float");

                    b.Property<double>("MounthlyPlus")
                        .HasColumnType("float");

                    b.Property<int>("NumberMounth")
                        .HasColumnType("int");

                    b.HasKey("MounthId");

                    b.ToTable("MounthlyDepozitReports");
                });
#pragma warning restore 612, 618
        }
    }
}
